sudo: required
services:
  - docker

before_install:
  - docker build -t gweinheimer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gweinheimer/react-test npm test

after_success:
  - docker build -t gweinheimer/multi-client ./client
  - docker build -t gweinheimer/multi-nginx ./nginx
  - docker build -t gweinheimer/multi-server ./server
  - docker build -t gweinheimer/multi-worker ./worker
# login to docker
# push images to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gweinheimer/multi-client  
  - docker push gweinheimer/multi-nginx  
  - docker push gweinheimer/multi-server  
  - docker push gweinheimer/multi-worker  
# deploy to AWS
deploy:
  provider: elastickbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-783616990833"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY





